excluded:
  - Carthage
  - glean-core/ios/Glean/Generated
  - samples/ios/app/Carthage
  - samples/ios/app/glean-sample-app/Generated
disabled_rules:
  - file_length
  # We're pretty careful about this already, but it's a pain to disable
  # and reenable in the cases where we're sure.
  - force_try
  # We'll get to these when we get to them!
  - todo

identifier_name:
  # Turn off it complaining about `id` or `let t = title`, etc, but keep
  # warnings around e.g. enum names.
  min_length:
    warning: 0
    error: 0

line_length:
  ignores_urls: true
