accepted = [
    "MPL-2.0",
    "Apache-2.0",
    "MIT",
    "CC0-1.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Zlib",
]

# Subset of targets we build for
targets = [
    # Linux/Windows/macOS
    "x86_64-unknown-linux-gnu",
    "x86_64-pc-windows-gnu",
    "x86_64-apple-darwin",

    # Android targets
    "aarch64-linux-android",
    "armv7-linux-androideabi",
    "i686-linux-android",
    "x86_64-linux-android",

    # iOS targets
    "aarch64-apple-ios",
    "x86_64-apple-ios"
]

ignore-build-dependencies = true
ignore-dev-dependencies = true
