// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

use std::fmt::Write;

use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use weedle::Definition::*;
use weedle::argument::Argument::{self, Single};
use weedle::interface::InterfaceMember;

use type_resolver::TypeResolver;

mod type_resolver;

const PREAMBLE: &str = r#"// DO NOT MODIFY!
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// This file is generated by tools/glean-sys-parser.
// Run `cargo test -p glean-sys` to regenerate it.
#![allow(clippy::all)]
#![cfg_attr(rustfmt, rustfmt_skip)]

use crate::types::*;
use crate::util::*;
"#;

#[derive(Default)]
struct FnArgs {
    arg_names: Vec<TokenStream>,
    fn_args: Vec<TokenStream>,
    extern_fn_args: Vec<TokenStream>,
    destroys: Vec<TokenStream>,
}

impl FnArgs {
    fn from_args(args: &[Argument<'_>]) -> Self {
        let mut this = Self::default();
        for arg in args {
            let Single(arg) = arg else { continue };
            let arg_name = format_ident!("{}", arg.identifier.0);
            let arg_type = arg.type_.type_.resolve();
            let extern_arg_type = arg.type_.type_.resolve_ffi();
            this.arg_names.push(quote! { #arg_name });
            this.fn_args.push(quote! { #arg_name: #arg_type });
            this.extern_fn_args
                .push(quote! { #arg_name: #extern_arg_type });
            this.destroys.push(quote! { #arg_name.destroy(); })
        }
        this.destroys.reverse();
        this
    }

    fn consume(
        self,
    ) -> (
        Vec<TokenStream>,
        Vec<TokenStream>,
        Vec<TokenStream>,
        Vec<TokenStream>,
    ) {
        (
            self.arg_names,
            self.fn_args,
            self.extern_fn_args,
            self.destroys,
        )
    }
}

pub fn generate(content: &str) -> String {
    let parsed = weedle::parse(content).unwrap();

    let mut tokens = vec![];
    let mut bindings = vec![];

    for elem in parsed {
        let Interface(iface) = elem else { continue };
        let ident = iface.identifier;
        if !ident.0.ends_with("Metric") {
            continue;
        }

        let structname = ident.0.to_lowercase().replace("_", "");
        let ident = format_ident!("{}", ident.0);
        let extern_fn_ident = format_ident!("uniffi_glean_core_fn_clone_{}", structname);
        tokens.push(quote! {
            #[derive(uniffi::Record)]
            pub struct #ident {
                handle: u64
            }

            impl #ident {
                unsafe fn clone_handle(&self) -> u64 {
                    unsafe {
                        let mut call_status = uniffi::RustCallStatus::default();
                        std::mem::transmute((crate::GLEAN.#extern_fn_ident)(std::mem::transmute(self.handle), &mut call_status))
                    }
                }
            }
        });
        bindings.push(quote! {
            fn #extern_fn_ident(handle: u64, call_status: &mut ::uniffi::RustCallStatus) -> u64;
        });

        let mut fns = vec![];
        let members = iface.members;
        for member in members.body {
            match member {
                InterfaceMember::Constructor(ctor) => {
                    let extern_fn_ident =
                        format_ident!("uniffi_glean_core_fn_constructor_{}_new", structname);
                    let all_args = FnArgs::from_args(&ctor.args.body.list);
                    let (arg_names, fn_args, extern_fn_args, destroys) = all_args.consume();
                    fns.push(quote! {
                        pub fn new(#(#fn_args,)*) -> Self {
                            unsafe {
                                #(
                                    let #arg_names = uniffi::FfiConverter::<crate::UniFfiTag>::lower(#arg_names);
                                )*
                                let mut call_status = uniffi::RustCallStatus::default();
                                let handle = (crate::GLEAN.#extern_fn_ident)(#(#arg_names.clone_for_ffi(),)* &mut call_status);
                                #(
                                    #destroys
                                )*
                                Self { handle }
                            }
                        }
                    });
                    bindings.push(quote! {
                        fn #extern_fn_ident(#(#extern_fn_args,)* call_status: &mut ::uniffi::RustCallStatus) -> u64;
                    });
                }
                InterfaceMember::Operation(op) => {
                    let Some(ident) = op.identifier else {
                        panic!("no identifier for op!")
                    };
                    let fn_ident = format_ident!("{}", ident.0);
                    let extern_fn_ident =
                        format_ident!("uniffi_glean_core_fn_method_{}_{}", structname, ident.0);
                    let ret_type = type_resolver::return_type(&op.return_type);
                    let extern_fn_ret_type = type_resolver::return_type_ffi(&op.return_type);

                    let all_args = FnArgs::from_args(&op.args.body.list);
                    let (arg_names, fn_args, extern_fn_args, destroys) = all_args.consume();

                    fns.push(quote! {
                        pub fn #fn_ident(&self, #(#fn_args),*) #ret_type {
                            unsafe {
                                let this = self.clone_handle();
                                #(
                                    let #arg_names = uniffi::FfiConverter::<crate::UniFfiTag>::lower(#arg_names);
                                )*
                                let mut call_status = uniffi::RustCallStatus::default();
                                let res = (crate::GLEAN.#extern_fn_ident)(this, #(#arg_names.clone_for_ffi(),)* &mut call_status);
                                #(
                                    #destroys
                                )*
                                uniffi::FfiConverter::<crate::UniFfiTag>::try_lift(res).unwrap()
                            }
                        }
                    });
                    bindings.push(quote! {
                        fn #extern_fn_ident(handle: u64, #(#extern_fn_args,)* call_status: &mut ::uniffi::RustCallStatus) #extern_fn_ret_type;
                    });
                }
                _ => todo!(),
            }
        }

        tokens.push(quote! {
            impl #ident {
                #(#fns)*
            }
        });
    }

    tokens.push(quote! {
        library_binding! {
            fn ffi_glean_core_rustbuffer_from_bytes(bytes: ::uniffi::ForeignBytes, call_status: &mut ::uniffi::RustCallStatus) -> ::uniffi::RustBuffer;
            #(#bindings)*
        }
    });

    let mut code = String::new();
    for token in tokens {
        writeln!(&mut code, "{token}").unwrap();
    }

    let mut output = String::new();
    writeln!(&mut output, "{PREAMBLE}").unwrap();
    let file = syn::parse_file(&code).unwrap();
    let code = prettyplease::unparse(&file);
    writeln!(&mut output, "{code}").unwrap();

    output
}
