use std::{collections::HashMap, sync::LazyLock, thread, time::Duration};

macro_rules! library_binding {
    ( $localname:ident members[$($members:tt)*] load[$($load:tt)*] fn $name:ident $args:tt $( -> $ret:ty )? ; $($rest:tt)* ) => {
        library_binding! {
            $localname
            members[
                $($members)*
                pub(crate) $name: libloading::Symbol<'static, unsafe extern "C" fn $args $(->$ret)?>,
            ]
            load[
                $($load)*
                $name: unsafe {
                    let symbol = $localname.get::<unsafe extern "C" fn $args $(->$ret)?>(stringify!($name).as_bytes())
                    .map_err(|e| std::io::Error::new(std::io::ErrorKind::NotFound, e))?;
                    // All symbols refer to library, so `'static` lifetimes are safe (`library`
                    // will outlive them).
                    std::mem::transmute(symbol)
                },
            ]
            $($rest)*
        }
    };
    ( $localname:ident members[$($members:tt)*] load[$($load:tt)*] ) => {
        pub struct GleanSys {
            $($members)*
            _library: libloading::Library,
        }

        impl GleanSys {
            #[cfg(unix)]
            pub fn load() -> std::io::Result<Self> {
                let name = "libxul.so";
                let library = match unsafe { libloading::Library::new(name) } {
                        Ok(lib) => {
                            Some(lib)
                        }
                        Err(e) => {
                            None
                        }
                };
                // Try each of the libraries, debug-logging load failures.
                let $localname = library.ok_or_else(|| {
                    std::io::Error::new(std::io::ErrorKind::NotFound, "failed to find glean library")
                })?;
                Ok(GleanSys { $($load)* _library: $localname })
            }

            #[cfg(not(unix))]
            pub fn load() -> std::io::Result<Self> {
                compile_error!("This crate is not implemented for Windows");
            }
        }
    };
    ( $($rest:tt)* ) => {
        library_binding! {
            library members[] load[] $($rest)*
        }
    }
}

pub mod metrics;
pub mod types;
mod util;
use metrics::*;
use types::*;

static GLEAN: LazyLock<GleanSys> = LazyLock::new(|| metrics::GleanSys::load().unwrap());

#[unsafe(no_mangle)]
extern "C" fn record_cat_name() {
    _ = &*GLEAN;

    let cmd = CommonMetricData {
        category: "cat".to_string(),
        name: "name".to_string(),
        send_in_pings: vec!["prototype".to_string()],
        lifetime: Lifetime::Ping,
        disabled: false,
        dynamic_label: None,
    };
    let metric = CounterMetric::new(cmd);
    metric.add(31);
    let value = metric.test_get_value(None);
    dbg!(value);

    let cmd = CommonMetricData {
        category: "cat".to_string(),
        name: "duration".to_string(),
        send_in_pings: vec!["prototype".to_string()],
        lifetime: Lifetime::Ping,
        disabled: false,
        dynamic_label: None,
    };
    let metric = TimespanMetric::new(cmd, types::TimeUnit::Microsecond);
    metric.start();
    thread::sleep(Duration::from_millis(100));
    metric.stop();
    let value = metric.test_get_value(None);
    dbg!(value);

    let cmd = CommonMetricData {
        category: "cat".to_string(),
        name: "event".to_string(),
        send_in_pings: vec!["prototype".to_string()],
        lifetime: Lifetime::Ping,
        disabled: false,
        dynamic_label: None,
    };
    let metric = EventMetric::new(cmd, vec!["some".to_string(), "extra".to_string()]);
    let extra = HashMap::from([
        ("some".to_string(), "value".to_string()),
        ("extra".to_string(), "byte".to_string()),
    ]);
    metric.record(extra);

    let value = metric.test_get_value(None);
    dbg!(value);
}

// This boilerplate is usually generated by `uniffi::setup_scaffolding!()`
// along with all the extra FFI functions, like wrappers around Rust buffer allocation, async handling, etc.
// We don't want to export those, so we do only the minimal part to support what `glean-sys` calls when used in other
// crates.

/// The crate-specific tag to implement traits.
#[doc(hidden)]
pub struct UniFfiTag;

/// The namespace glean-sys FFI items are placed in.
/// Required by UniFFI to match up items.
const UNIFFI_META_CONST_NAMESPACE_GLEAN_SYS: ::uniffi::MetadataBuffer = ::uniffi::MetadataBuffer::from_code(
        ::uniffi::metadata::codes::NAMESPACE,
    )
    .concat_str("glean_sys")
    .concat_str("glean_sys");
#[doc(hidden)]
#[unsafe(no_mangle)]
pub static UNIFFI_META_NAMESPACE_GLEAN_SYS: [::std::primitive::u8; UNIFFI_META_CONST_NAMESPACE_GLEAN_SYS
    .size] = UNIFFI_META_CONST_NAMESPACE_GLEAN_SYS.into_array();
