// DO NOT MODIFY!
// This file is generated by tools/glean-sys-parser.
// Run `cargo run -p glean-sys-parser glean-core/src/glean.udl` to regenerate it.

use uniffi::HandleAlloc;
use uniffi::FfiConverter;

unsafe extern "C" {
    unsafe fn uniffi_glean_core_fn_method_countermetric_add(
        uniffi_self_lowered: <<glean_core::CounterMetric as ::uniffi::LiftRef<
        glean_core::UniFfiTag,
        >>::LiftType as ::uniffi::Lift<glean_core::UniFfiTag>>::FfiType,
        amount: <i32 as ::uniffi::Lift<glean_core::UniFfiTag>>::FfiType,
        call_status: &mut ::uniffi::RustCallStatus,
    ) -> <() as ::uniffi::LowerReturn<glean_core::UniFfiTag>>::ReturnType;

    unsafe fn uniffi_glean_core_fn_method_countermetric_test_get_value(
        uniffi_self_lowered: <<glean_core::CounterMetric as ::uniffi::LiftRef<
            glean_core::UniFfiTag,
        >>::LiftType as ::uniffi::Lift<glean_core::UniFfiTag>>::FfiType,
        ping_name: <::std::option::Option<
            ::std::string::String,
        > as ::uniffi::Lift<glean_core::UniFfiTag>>::FfiType,
        call_status: &mut ::uniffi::RustCallStatus,
    ) -> <::std::option::Option<i32> as ::uniffi::LowerReturn<glean_core::UniFfiTag>>::ReturnType;

    unsafe fn uniffi_glean_core_fn_clone_countermetric(
        handle: ::uniffi::ffi::Handle,
        call_status: &mut ::uniffi::RustCallStatus,
    ) -> ::uniffi::ffi::Handle;
}

struct Rate {
    numerator: i32,
    denominator: i32,
}

type JsonValue = String;
struct RecordedEvent {
    timestamp: u64,
    category: String,
    name: String,
    extra: Option<::std::collections::HashMap<String, String>>,
}

struct Datetime {
    year: i32,
    month: u32,
    day: u32,
    hour: u32,
    minute: u32,
    second: u32,
    nanosecond: u32,
    offset_seconds: i32,
}

struct DistributionData {
    values: ::std::collections::HashMap<i64, i64>,
    sum: i64,
    count: i64,
}

struct TimerId {
    id: u64,
}

enum ErrorType {
    InvalidValue,
    InvalidLabel,
    InvalidState,
    InvalidOverflow,
}

struct CounterMetric {
    handle: u64,
}
impl CounterMetric {
    fn new() -> Self {
        todo!()
    }
    unsafe fn clone_handle(&self) -> uniffi::Handle {
        let mut call_status = uniffi::RustCallStatus::default();
        uniffi_glean_core_fn_clone_countermetric(std::mem::transmute(self.handle), &mut call_status)
    }
    fn add(&self, amount: i32) -> () {
        unsafe {
            let mut call_status = uniffi::RustCallStatus::default();
            let amount = FfiConverter::<glean_core::UniFfiTag>::lower(amount);

            uniffi_glean_core_fn_method_countermetric_add(self.clone_handle(), amount, &mut call_status)
        }
    }
    fn test_get_value(&self, ping_name: Option<String>) -> Option<i32> {
        unsafe {
            let mut call_status = uniffi::RustCallStatus::default();
            let ping_name = FfiConverter::<glean_core::UniFfiTag>::lower(ping_name);

            FfiConverter::<glean_core::UniFfiTag>::try_lift(
                uniffi_glean_core_fn_method_countermetric_test_get_value(self.clone_handle(), ping_name, &mut call_status)
            ).unwrap()
        }
    }
    fn test_get_num_recorded_errors(&self, error: ErrorType) -> i32 {
        todo!()
    }
}
struct TimespanMetric {
    handle: u64,
}
impl TimespanMetric {
    fn new() -> Self {
        todo!()
    }
    fn start(&self) -> () {
        todo!()
    }
    fn stop(&self) -> () {
        todo!()
    }
    fn cancel(&self) -> () {
        todo!()
    }
    fn set_raw_nanos(&self, elapsed: i64) -> () {
        todo!()
    }
    fn test_get_value(&self, ping_name: Option<String>) -> Option<i64> {
        todo!()
    }
    fn test_get_num_recorded_errors(&self, error: ErrorType) -> i32 {
        todo!()
    }
}
struct BooleanMetric {
    handle: u64,
}
impl BooleanMetric {
    fn new() -> Self {
        todo!()
    }
    fn set(&self, value: bool) -> () {
        todo!()
    }
    fn test_get_value(&self, ping_name: Option<String>) -> Option<bool> {
        todo!()
    }
    fn test_get_num_recorded_errors(&self, error: ErrorType) -> i32 {
        todo!()
    }
}
struct StringMetric {
    handle: u64,
}
impl StringMetric {
    fn new() -> Self {
        todo!()
    }
    fn set(&self, value: String) -> () {
        todo!()
    }
    fn test_get_value(&self, ping_name: Option<String>) -> Option<String> {
        todo!()
    }
    fn test_get_num_recorded_errors(&self, error: ErrorType) -> i32 {
        todo!()
    }
}
struct StringListMetric {
    handle: u64,
}
impl StringListMetric {
    fn new() -> Self {
        todo!()
    }
    fn add(&self, value: String) -> () {
        todo!()
    }
    fn set(&self, value: Vec<String>) -> () {
        todo!()
    }
    fn test_get_value(&self, ping_name: Option<String>) -> Option<Vec<String>> {
        todo!()
    }
    fn test_get_num_recorded_errors(&self, error: ErrorType) -> i32 {
        todo!()
    }
}
struct UrlMetric {
    handle: u64,
}
impl UrlMetric {
    fn new() -> Self {
        todo!()
    }
    fn set(&self, value: String) -> () {
        todo!()
    }
    fn test_get_value(&self, ping_name: Option<String>) -> Option<String> {
        todo!()
    }
    fn test_get_num_recorded_errors(&self, error: ErrorType) -> i32 {
        todo!()
    }
}
struct UuidMetric {
    handle: u64,
}
impl UuidMetric {
    fn new() -> Self {
        todo!()
    }
    fn set(&self, value: String) -> () {
        todo!()
    }
    fn generate_and_set(&self) -> String {
        todo!()
    }
    fn test_get_value(&self, ping_name: Option<String>) -> Option<String> {
        todo!()
    }
    fn test_get_num_recorded_errors(&self, error: ErrorType) -> i32 {
        todo!()
    }
}
struct QuantityMetric {
    handle: u64,
}
impl QuantityMetric {
    fn new() -> Self {
        todo!()
    }
    fn set(&self, value: i64) -> () {
        todo!()
    }
    fn test_get_value(&self, ping_name: Option<String>) -> Option<i64> {
        todo!()
    }
    fn test_get_num_recorded_errors(&self, error: ErrorType) -> i32 {
        todo!()
    }
}
struct TimingDistributionMetric {
    handle: u64,
}
impl TimingDistributionMetric {
    fn new() -> Self {
        todo!()
    }
    fn start(&self) -> TimerId {
        todo!()
    }
    fn stop_and_accumulate(&self, timer_id: TimerId) -> () {
        todo!()
    }
    fn cancel(&self, timer_id: TimerId) -> () {
        todo!()
    }
    fn accumulate_samples(&self, samples: Vec<i64>) -> () {
        todo!()
    }
    fn accumulate_single_sample(&self, sample: i64) -> () {
        todo!()
    }
    fn test_get_value(&self, ping_name: Option<String>) -> Option<DistributionData> {
        todo!()
    }
    fn test_get_num_recorded_errors(&self, error: ErrorType) -> i32 {
        todo!()
    }
}
struct MemoryDistributionMetric {
    handle: u64,
}
impl MemoryDistributionMetric {
    fn new() -> Self {
        todo!()
    }
    fn accumulate(&self, sample: i64) -> () {
        todo!()
    }
    fn accumulate_samples(&self, samples: Vec<i64>) -> () {
        todo!()
    }
    fn test_get_value(&self, ping_name: Option<String>) -> Option<DistributionData> {
        todo!()
    }
    fn test_get_num_recorded_errors(&self, error: ErrorType) -> i32 {
        todo!()
    }
}
struct CustomDistributionMetric {
    handle: u64,
}
impl CustomDistributionMetric {
    fn new() -> Self {
        todo!()
    }
    fn accumulate_samples(&self, samples: Vec<i64>) -> () {
        todo!()
    }
    fn accumulate_single_sample(&self, sample: i64) -> () {
        todo!()
    }
    fn test_get_value(&self, ping_name: Option<String>) -> Option<DistributionData> {
        todo!()
    }
    fn test_get_num_recorded_errors(&self, error: ErrorType) -> i32 {
        todo!()
    }
}
struct DatetimeMetric {
    handle: u64,
}
impl DatetimeMetric {
    fn new() -> Self {
        todo!()
    }
    fn set(&self, value: Option<Datetime>) -> () {
        todo!()
    }
    fn test_get_value(&self, ping_name: Option<String>) -> Option<Datetime> {
        todo!()
    }
    fn test_get_value_as_string(&self, ping_name: Option<String>) -> Option<String> {
        todo!()
    }
    fn test_get_num_recorded_errors(&self, error: ErrorType) -> i32 {
        todo!()
    }
}
struct EventMetric {
    handle: u64,
}
impl EventMetric {
    fn new() -> Self {
        todo!()
    }
    fn record(&self, extra: ::std::collections::HashMap<String, String>) -> () {
        todo!()
    }
    fn test_get_value(&self, ping_name: Option<String>) -> Option<Vec<RecordedEvent>> {
        todo!()
    }
    fn test_get_num_recorded_errors(&self, error: ErrorType) -> i32 {
        todo!()
    }
}
struct RateMetric {
    handle: u64,
}
impl RateMetric {
    fn new() -> Self {
        todo!()
    }
    fn add_to_numerator(&self, amount: i32) -> () {
        todo!()
    }
    fn add_to_denominator(&self, amount: i32) -> () {
        todo!()
    }
    fn test_get_value(&self, ping_name: Option<String>) -> Option<Rate> {
        todo!()
    }
    fn test_get_num_recorded_errors(&self, error: ErrorType) -> i32 {
        todo!()
    }
}
struct DenominatorMetric {
    handle: u64,
}
impl DenominatorMetric {
    fn new() -> Self {
        todo!()
    }
    fn add(&self, amount: i32) -> () {
        todo!()
    }
    fn test_get_value(&self, ping_name: Option<String>) -> Option<i32> {
        todo!()
    }
    fn test_get_num_recorded_errors(&self, error: ErrorType) -> i32 {
        todo!()
    }
}
struct NumeratorMetric {
    handle: u64,
}
impl NumeratorMetric {
    fn new() -> Self {
        todo!()
    }
    fn add_to_numerator(&self, amount: i32) -> () {
        todo!()
    }
    fn test_get_value(&self, ping_name: Option<String>) -> Option<Rate> {
        todo!()
    }
    fn test_get_num_recorded_errors(&self, error: ErrorType) -> i32 {
        todo!()
    }
}
struct TextMetric {
    handle: u64,
}
impl TextMetric {
    fn new() -> Self {
        todo!()
    }
    fn set(&self, value: String) -> () {
        todo!()
    }
    fn test_get_value(&self, ping_name: Option<String>) -> Option<String> {
        todo!()
    }
    fn test_get_num_recorded_errors(&self, error: ErrorType) -> i32 {
        todo!()
    }
}
struct ObjectMetric {
    handle: u64,
}
impl ObjectMetric {
    fn new() -> Self {
        todo!()
    }
    fn set_string(&self, object: String) -> () {
        todo!()
    }
    fn test_get_value(&self, ping_name: Option<String>) -> Option<JsonValue> {
        todo!()
    }
    fn test_get_num_recorded_errors(&self, error: ErrorType) -> i32 {
        todo!()
    }
    fn record_schema_error(&self) -> () {
        todo!()
    }
}
struct DualLabeledCounterMetric {
    handle: u64,
}
impl DualLabeledCounterMetric {
    fn new() -> Self {
        todo!()
    }
    fn get(&self, key: String, category: String) -> CounterMetric {
        todo!()
    }
    fn test_get_value(
        &self,
        ping_name: Option<String>,
    ) -> Option<::std::collections::HashMap<String, ::std::collections::HashMap<String, i32>>> {
        todo!()
    }
    fn test_get_num_recorded_errors(&self, error: ErrorType) -> i32 {
        todo!()
    }
}

