// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

use std::fs::File;
use std::io::Write;
use std::path::Path;

pub fn is_first_run(data_path: &str) -> bool {
    let path = Path::new(data_path);
    let path = path.join("glean_first_run.txt");

    if path.exists() {
        return false;
    }

    let mut file = File::create(path).unwrap();
    file.write_all(b"# DO NOT TOUCH - AUTO GENERATED BY GLEAN.RS")
        .unwrap();

    true
}
