[bindings.kotlin]
package_name = "mozilla.telemetry.glean.internal"
cdylib_name = "glean_ffi"

[bindings.swift]
cdylib_name = "glean_ffi"
omit_argument_labels = true

[bindings.python]
cdylib_name = "glean_ffi"
