[book]
title = "Glean - Cross-platform Telemetry library"
authors = ["Jan-Erik Rediger", "Glean Team"]
src = "."

[build]
build-dir = "book"
create-missing = false

[output.html]
additional-css = ["glean.css", "mermaid.css"]
additional-js = ["tabs.js", "mermaid.min.js", "mermaid-init.js", "chart.min.js", "chart-distributions.js", "chart-distributions-ui.js"]
git-repository-url = "https://github.com/mozilla/glean"
git-branch = "main"
mathjax-support = true

[preprocessor.open-on-gh]
command = "mdbook-open-on-gh"

[preprocessor.mermaid]
command = "mdbook-mermaid"
