/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

package mozilla.telemetry.glean.private

import androidx.annotation.VisibleForTesting
import mozilla.telemetry.glean.testing.ErrorType
import mozilla.telemetry.glean.internal.LabeledBoolean as InternalLabeledBoolean
import mozilla.telemetry.glean.internal.LabeledCounter as InternalLabeledCounter
import mozilla.telemetry.glean.internal.LabeledCustomDistribution as InternalLabeledCustomDistribution
import mozilla.telemetry.glean.internal.LabeledMemoryDistribution as InternalLabeledMemoryDistribution
import mozilla.telemetry.glean.internal.LabeledQuantity as InternalLabeledQuantity
import mozilla.telemetry.glean.internal.LabeledString as InternalLabeledString
import mozilla.telemetry.glean.internal.LabeledTimingDistribution as InternalLabeledTimingDistribution

class LabeledBoolean constructor(
    meta: LabeledMetricData,
    labels: List<String>?,
) {
    val metric = InternalLabeledBoolean(meta, labels)

    fun get(label: String): BooleanMetricType = BooleanMetricType(metric.get(label))
}

class LabeledCounter constructor(
    meta: LabeledMetricData,
    labels: List<String>?,
) {
    val metric = InternalLabeledCounter(meta, labels)

    fun get(label: String): CounterMetricType = CounterMetricType(metric.get(label))
}

class LabeledQuantity constructor(
    meta: LabeledMetricData,
    labels: List<String>?,
) {
    val metric = InternalLabeledQuantity(meta, labels)

    fun get(label: String): QuantityMetricType = QuantityMetricType(metric.get(label))
}

class LabeledString constructor(
    meta: LabeledMetricData,
    labels: List<String>?,
) {
    val metric = InternalLabeledString(meta, labels)

    fun get(label: String): StringMetricType = StringMetricType(metric.get(label))
}

class LabeledMemoryDistribution constructor(
    meta: LabeledMetricData,
    labels: List<String>?,
) {
    val metric = InternalLabeledMemoryDistribution(meta, labels)

    fun get(label: String): MemoryDistributionMetricType = MemoryDistributionMetricType(metric.get(label))
}

class LabeledTimingDistribution constructor(
    meta: LabeledMetricData,
    labels: List<String>?,
) {
    val metric = InternalLabeledTimingDistribution(meta, labels)

    fun get(label: String): TimingDistributionMetricType = TimingDistributionMetricType(metric.get(label))
}

class LabeledCustomDistribution constructor(
    meta: LabeledMetricData,
    labels: List<String>?,
) {
    val metric = InternalLabeledCustomDistribution(meta, labels)

    fun get(label: String): CustomDistributionMetricType = CustomDistributionMetricType(metric.get(label))
}

/**
 * This implements the developer facing API for labeled metrics.
 *
 * Instances of this class type are automatically generated by the parsers at build time,
 * allowing developers to record values that were previously registered in the metrics.yaml file.
 *
 * Unlike most metric types, LabeledMetricType does not have its own corresponding storage,
 * but records metrics for the underlying metric type T in the storage for that type.  The
 * only difference is that labeled metrics are stored with the special key
 * `$category.$name/$label`. The collect method knows how to pull these special values back
 * out of the individual metric storage and rearrange them correctly in the ping.
 */
@Suppress("LongParameterList")
class LabeledMetricType<T>(
    private val meta: LabeledMetricData,
    private val subMetric: T,
    private val labels: Set<String>? = null,
) {
    // The inner labeled metric, from which actual metrics are constructed.
    private val inner: Any

    init {
        this.inner = when (subMetric) {
            is CounterMetricType -> LabeledCounter(meta, labels?.toList())
            is BooleanMetricType -> LabeledBoolean(meta, labels?.toList())
            is StringMetricType -> LabeledString(meta, labels?.toList())
            is QuantityMetricType -> LabeledQuantity(meta, labels?.toList())
            is CustomDistributionMetricType -> LabeledCustomDistribution(meta, labels?.toList())
            is MemoryDistributionMetricType -> LabeledMemoryDistribution(meta, labels?.toList())
            is TimingDistributionMetricType -> LabeledTimingDistribution(meta, labels?.toList())
            else -> error("Can not create a labeled version of this metric type")
        }
    }

    /**
     * Get the specific metric for a given label.
     *
     * If a set of acceptable labels were specified in the metrics.yaml file,
     * and the given label is not in the set, it will be recorded under the
     * special `__other__`.
     *
     * If a set of acceptable labels was not specified in the metrics.yaml file,
     * only the first 16 unique labels will be used. After that, any additional
     * labels will be recorded under the special `__other__` label.
     *
     * Labels must have a maximum of 111 characters, and may comprise any printable ASCII characters.
     * is used, the metric will be recorded in the special `__other__` label.
     *
     * @param label The label
     * @return The specific metric for that label
     */
    @Suppress("UNCHECKED_CAST")
    operator fun get(label: String): T =
        when (this.inner) {
            is LabeledCounter -> this.inner.get(label) as T
            is LabeledBoolean -> this.inner.get(label) as T
            is LabeledString -> this.inner.get(label) as T
            is LabeledQuantity -> this.inner.get(label) as T
            is LabeledCustomDistribution -> this.inner.get(label) as T
            is LabeledMemoryDistribution -> this.inner.get(label) as T
            is LabeledTimingDistribution -> this.inner.get(label) as T
            else -> error("Can not create a labeled version of this metric type")
        }

    /**
     * Get the specific metric for a given label index.
     *
     * This only works if a set of acceptable labels were specified in the
     * metrics.yaml file. If static labels were not defined in that file or
     * the index of the given label is not in the set, it will be recorded under
     * the special `__other__`.
     *
     * @param labelIndex The label
     * @return The specific metric for that label
     */
    operator fun get(labelIndex: Int): T {
        val actualLabel = if (labels != null && labelIndex < labels.size) {
            labels.elementAt(labelIndex)
        } else {
            "__other__"
        }

        return this[actualLabel]
    }

    /**
     * Returns the number of errors recorded for the given metric.
     *
     * @param error The type of the error recorded.
     * @return the number of errors recorded for the metric.
     */
    @VisibleForTesting(otherwise = VisibleForTesting.NONE)
    fun testGetNumRecordedErrors(errorType: ErrorType): Int =
        when (this.inner) {
            is LabeledCounter -> this.inner.metric.testGetNumRecordedErrors(errorType)
            is LabeledBoolean -> this.inner.metric.testGetNumRecordedErrors(errorType)
            is LabeledString -> this.inner.metric.testGetNumRecordedErrors(errorType)
            is LabeledQuantity -> this.inner.metric.testGetNumRecordedErrors(errorType)
            is LabeledCustomDistribution -> this.inner.metric.testGetNumRecordedErrors(errorType)
            is LabeledMemoryDistribution -> this.inner.metric.testGetNumRecordedErrors(errorType)
            is LabeledTimingDistribution -> this.inner.metric.testGetNumRecordedErrors(errorType)
            else -> error("Can not create a labeled version of this metric type")
        }

    /**
     * Returns the currently stored values for each label as the appropriate type for the given
     * metric.
     *
     * This doesn't clear the stored value.
     *
     * @param pingName The optional name of the ping to retrieve the metrics for. Defaults to the
     *   first value in `send_in_pings`.
     * @return The values for each label in the labeled metric.
     */
    @VisibleForTesting(otherwise = VisibleForTesting.NONE)
    fun testGetValue(pingName: String? = null): Map<String, Any> =
        when (this.inner) {
            is LabeledBoolean -> this.inner.metric.testGetValue(pingName)
            is LabeledCounter -> this.inner.metric.testGetValue(pingName)
            is LabeledString -> this.inner.metric.testGetValue(pingName)
            is LabeledQuantity -> this.inner.metric.testGetValue(pingName)
            is LabeledCustomDistribution -> this.inner.metric.testGetValue(pingName)
            is LabeledMemoryDistribution -> this.inner.metric.testGetValue(pingName)
            is LabeledTimingDistribution -> this.inner.metric.testGetValue(pingName)
            else -> error("Can not create a labeled version of this metric type")
        }!!
}
