---
name: Glean probe-scraper
on:
  pull_request:
  push:
    branches: main

jobs:
  glean-probe-scraper:
    uses: mozilla/probe-scraper/.github/workflows/glean.yaml@4afad6a635c7e413d1de7c63e74480ff7720c13a
